app/basketball/page.tsx, package-lock.json
- I deleted the waitlist section from the basketball page.
---
- The basketball facility is open so no need for a waitlist. 
---
- [✓ ] Frontend tested locally (`npm run dev`)
---
https://trello.com/c/YlPkbPSk/63-basketball-page-delete-join-waitlist
---
- There is one console error that I have seen since the start. it says it is a hydration mismatch. Will add to trello and look into it.
=> [Chore] Deleted the waitlist section from the basketball page

app/barber/page.tsx
- Changed Schedule a Barber Appointment to Schedule a Courtside Cut.
---
- Made the change so booking relates to what we call the barber area.
---
---
---
https://trello.com/c/C00G6mO0/75-barber-page-schedule-appointment-header-change
---
=> [Chore] Changed Schedule a Barber Appointment to Schedule a Courtside Cut

app/barber/page.tsx
- Removed waitlist section from the Barber Page
---
- The Barber is open at the facility so no need for a waitlist
---
---
https://trello.com/c/OsokNvs2/83-barber-page-delete-join-waitlist
---
=> [Chore] Removed waitlist section from barber page

app/page.tsx, components/ui/membership-card.tsx
- Added routes to all the JOIN NOW buttons on the home page. They all go to /join
---
- Added this so the buttons will take the users to a join page
---
---
https://trello.com/c/yEfhQRyq/33-home-page-join-now-buttons
---
- Lots of formatting changes from Prettier
=> [Chore] Added routes to all JOIN NOW buttons on the home page

app/supplements/page.tsx, components/ui/product-card.tsx
- Changed all Add to Cart or Shop Now buttons to Coming Soon
- Deleted a placeholder for the PRORISE image from the video hero section
---
- Supplements is not open at the facility so changed it all to Coming Soon
- Deleted placeholder till an image is available, was giving a code error so deleted it for the mean time
---
---
https://trello.com/c/pGOHUF6i/92-supplements-page-change-buttons-to-coming-soon
---
=> [Chore] Changed all add to cart or shop now buttons to "COMING SOON"

app/basketball/page.tsx
- Changed memberships to Basketball Memberships
---
- Made this change since the basketball page only displays basketball memberships and none of the other kinds. 
---
---
---
https://trello.com/c/qT9KEPma/59-basketball-page-memberships-change-to-basketball-memberships
=> [Chore] Changed memberships to Basketball Memberships

app/coffee/page.tsx, components/countdown-timer.tsx
- Styled countdown timer for mobile view
- Deleted Placeholder for image in VideoHero section
---
- Styled countdown timer so end users can see it on mobile view (it was getting cut off the sides)
- Deleted placeholder since it was giving an error in the code
---
---
---
https://trello.com/c/m4hgMRU5/88-coffee-page-countdown-timer-style-for-mobile-view
---
=> [Chore] Styled countdown timer for mobile view

app/reviews/page.tsx, components/ui/animated-text.tsx
- Centered the Customer Reviews header
---
- Centered it for consistent styles across the whole website 
---
---
https://trello.com/c/nQ7LRqBw/100-reviews-page-main-screen-styles
---
=> [Chore] Centered Customer Reviews Header

app/page.tsx, components/ui/membership-card.tsx
- Added links to Learn More buttons
---
- Added links so when users click they go to a learn more page
---
---
https://trello.com/c/VdTtcYWJ/38-home-page-membership
---
=> [Chore] Added learn more links to button on home page

app/coffee/page.tsx, components/ui/waitlist-form.tsx
- Adjusted waitlist form component so there's no title
- Used same styling as footer for Coffee waitlist input and submit
---
- Took the join waitlist title off the component so each different waitlists have different titles
- Used same styling so it is consistent and clean 
---
---
---
https://trello.com/c/xZrvK5J3/89-coffee-page-join-waitlist-styles
---
=> [Chore] Fixed join coffee waitlist styles

app/supplements/page.tsx, components/ui/section-heading.tsx
- Changed waitlist style to match Coffee waitlist styles
---
- Made this change so waitlist styles are consistent 
---
---
https://trello.com/c/B1Dt1cQi/96-supplements-page-change-join-waitlist
---
=> [Chore] Fixed supplements Join Waitlist styles

app/basketball/page.tsx
- Changed Animated text to Section Header 
- Centered styles
---
- Made this change so header is fully readable on mobile view
---
---
---
https://trello.com/c/J7801iq8/61-basketball-page-dreams-become-achievements-styles
---
=> [Chore] Fixed mobile view for dreams become achievements header

app/contact/page.tsx, components/ui/contact-form.tsx, components/ui/contact-info.tsx
- Changed styling so on web the cards are the same size
- Changed "Application Form" to "Contact Us"
- Added "Questions" in front of "Get in touch"
---
- Changed styles so cards look even instead off different shapes
- Changed headers since you're asking a question not filling out an application form
---
---
https://trello.com/c/2WHVrwEh/99-contact-page-edit-forms
---
=> [Chore] Changed styling and headers of contact us / got questions cards

lib/constants.ts
- Added GREAT VALUE to all memberships other than RISE Full Year
---
- Added great value so people will be persuaded to buy the full year membership which says BEST VALUE
---
---
---
- https://trello.com/c/VKzCGlLM/39-home-page-membership-value-badge-addition-good-value
- https://trello.com/c/wG3ZSrJm/69-performance-page-memberships-add-badges-great-value
- https://trello.com/c/8bTTAbiz/58-basketball-page-memberships-add-great-value-badge-to-jr-memby
---
- This fix will cover multiple Trello Cards
=> [Chore] Added GREAT VALUE badges to membership cards

app/layout.tsx, app/page.tsx, components/ui/plan-comparison-table.tsx
-  Fixed comparison plan styling to make look nicer and more interaction, better ui overall.
- Optimized it for mobile view as well.
- 
---
To improve the styling of the website 
---
---
---
https://trello.com/c/sl6drZX5/41-home-page-compare-plans-filter
---
=> [Chore] Changed styling of comparison plan on homepage

app/coaches/layout.tsx, app/coaches/page.tsx, components/ui/parallax-section.tsx, components/ui/section-container.tsx
- Added all coaches page
---
- Added it so user can see all of the coaches that work at and for RISE
---
---
https://trello.com/c/z1mgnGJF/112-add-all-coaches-page
---
- Still need to add API so current coaches are placeholders
=> [Feature] Added All Coaches page

app/api/Api.ts, app/api/docs/swagger.json, app/page.tsx, components/membershipsSection.tsx, components/ui/membership-grid.tsx, configs/constants.ts, hooks/useMembershipPlans.ts, services/membership.ts, types/membership.ts
- Added Api folder and file
- Added export to membershipplan interface in the membership-grid component
- added membershipsection component
- added configs folder with constants file
- added membership hook
- added services folder with membership file
- added types folder with membership file
- changed home page section to only display membership section component
---
- Added api files so we can access the backend response formats 
- Added export to member ship plan interface so I could use it as a type and import it into my usemembershipsplans hook
- Added this so it takes the membership grid component so all styling on membership cards will be exact same, it also connects to the hook which gets all the data from the membership services api request
- configs folder and constants file …
=> [Feature] Added API request to the home page for memberships

app/allmemberships/page.tsx, app/api/Api.ts, app/memberships/[id]/page.tsx, services/membershipPlan.ts, types/membership.ts
- Added all memberships page
- Added dynamic route memberships page
- Added membershipPlan service
- Added interface type for membership plan
- Added to API.ts for membership plan response 
---
- A new page that fetches and displays every available membership in a responsive grid, complete with badge labels, “Starting at” pricing, and a “View Plans” button on each card.
- A /memberships/[id] route that looks up a single membership by its ID, renders its name, description.
- A client‑side module (services/membershipPlan.ts) that fetches plan data for a given membership ID from the /memberships/{id}/plans endpoint and maps the API response into your MembershipPlan shape.
- A TypeScript interface in @/types/membership.ts defining the structure of each plan—fields like id, membership_id, …
=> [Feature] Added Membership pages to view and select a membership to purchase

app/page.tsx
- Changed background video
- Changed route for buttons 
---
- Changed the video since it was a placeholder before
- Changed route for buttons so it takes you to memberships on the current page or the all memberships page 
---
---
https://trello.com/c/h76XsJjQ/152-home-page-main-screen-styles-buttons
---
=> [Chore] Changed Main Page background video and buttons

app/basketball/page.tsx
- Added new background video
- Added scroll arrow
- Routed buttons
---
- Added background video to replace placeholder
- Added scroll arrow so it has same styles on primary pages
- Routed buttons so users will learn more or go to all memberships page to purchase
---
---
https://trello.com/c/qdM9suCn/43-basketball-page-main-screen-styles-buttons
---
=> [Chore] Changed Basketball Page background video and buttons

app/performance/page.tsx
- Added background video 
- Added scroll arrow
- Routed buttons
---
- Replaced the placeholder video
- Added scroll arrow to follow same styling on primary pages
- Routed buttons so they take users to correct pages
---
---
https://trello.com/c/lUlvrDxq/64-performance-page-main-screen-styles-buttons
---
=> [Chore] Changed Performance Page background video and buttons

app/barber/page.tsx
- Added new background video
- Added scroll arrow
- Routed buttons
---
- New video to replace placeholder
- Added scroll arrow to match styles of primary pages
- Routed buttons so you can book a haircut or view previous cuts 
---
---
https://trello.com/c/hFb0v3t3/72-barber-page-main-screen-styles-buttons
---
=> [Chore] Changed Barber Page background video and buttons

app/signup/page.tsx
Changed title on sign up page
---
Make the user experience better
---
- x[ ] No console errors (Frontend)
---
---
=> [Chore] Changed Title on Signup page

app/login/page.tsx
- Created new login page and new file with the ui
- 
- 
---
in order for users to also be able to login
---
- [x ] Backend APIs tested via Postman
---
---
=> [Feature] Added login page for users

app/api/Api.ts, app/basketball/page.tsx, components/scheduleCalendar.tsx, components/ui/calendar.tsx, services/eventsCalendar.ts, services/gamesCalendar.ts, types/event.ts, types/game.ts
- Added scheduleCalendar component
- Added event type
- Added eventsCalednar service
- Changed calendar component
- Added gamesCalendar service
- Added game type
---
- Added scheduleCalendar component: encapsulates the calendar UI and custom rendering logic to display scheduled events on their respective dates.
- Added Event type: defines a TypeScript interface for events, ensuring consistent, type‑safe access to all event properties.
- Added eventsCalendar service: provides dedicated functions to fetch and transform “other” and “course” events from the API into the shape required by the calendar.
- Changed calendar component: extends the base DayPicker to support custom day content, event‑type pills, and tailored navigation styling.
- Added gamesCalendar service: fetches and normalizes …
=> [Feature] Added calendar to the basketball page for schedule 

app/checkout/page.tsx, app/login/page.tsx, app/memberships/[id]/page.tsx, services/membership.ts, services/membershipPlan.ts
-  Kyle and I fixed and implemented the membership checkout flow
-  Users now can pick a membership and be redirected to stripes webhook for checkout
---
Users are going to need to be able to buy memberships and have them tied to their account!
---
---
https://trello.com/c/ffZnbcIo/159-implement-membership-checkout
---
Should be good we can test together and all go through it if needed
=> [Feature] Membership checkout flow

app/globals.css, app/layout.tsx, app/signup/page.tsx, package-lock.json, package.json
Updated waiver_signed logic to correctly set is_waiver_signed: true on all waiver objects
Integrated react-phone-number-input with custom Tailwind styles
Removed grey box issue and aligned the country flag dropdown inside the input field
Removed redundant phone icon and improved padding consistency
---
Users were unable to proceed with registration even after checking the waiver checkbox due to only the first waiver being flagged
The phone number field looked visually inconsistent with the rest of the form and didn’t properly support international formatting or country code selection
---
---
---
https://trello.com/c/b06gSZ1d/154-waivers-causing-registering-error
=> [Bugfix] Fixed Waivers Error and Phone Number formatting

app/signup/page.tsx
- Validation added to all input fields to make sure form can't be submitted without some information
---
So people cannot submit empty information and cause errors in our backend 
---
- [x ] No server errors (Backend)
---
---
=> [Bugfix] Added validation for input fields

app/basketball/page.tsx, app/layout.tsx, app/performance/page.tsx, components/basketballMembershipSection.tsx, components/performanceMembershipSection.tsx, components/ui/membership-card.tsx, hooks/useMembershipPlans.ts, lib/constants.ts
- Created basketball membership section component
- Created performance membership section component
- Changed membership hook
- Called basketball membership component
- Called performance membership component
---
- Created basketball / performance membership components to call specific cards to display on the page
- Changed membership hook to include starting at prices
- Called components into the pages so they will display fir users to see
---
---
- https://trello.com/c/9hyhWjPg/158-use-memberships-api-component-baksetball-performance
- https://trello.com/c/7JS3A4m4/147-memberships-hard-code-price-starting-at
---
=> [Chore] Used APIs for Performance and Basketball membership sections 

app/barber/page.tsx, app/basketball/page.tsx, app/page.tsx, app/performance/page.tsx, components/ui/membership-card.tsx
- Rerouted all JOIN NOW buttons
- Deleted unused buttons 
---
- Re routed buttons so it takes you to glo fox so users can buy memberships
- Deleted unused buttons so users 
---
---
- https://trello.com/c/PuE8OzVf/163-route-join-now-buttons-to-glofox
- https://trello.com/c/29Wa2EeB/62-basketball-page-premier-team-link
---
=> routed join now buttons to glo fox, deleted unused buttons

app/api/subscribe/route.ts, app/coffee/page.tsx, app/supplements/page.tsx, components/newsletter-form.tsx, package-lock.json, package.json
Updated /api/subscribe/route.ts to support Mailchimp tagging 
Integrated blueimp-md5 to generate subscriber hashes in Edge-compatible environments
---
To allow segmented newsletter signups across the site (e.g., coffee, supplements, general),
---
=> [Feature]Add Mailchimp tagging and graceful handling for deleted subscribers

app/layout.tsx, components/newsletter-form.tsx
- Added toast in responses 
---
- Added this so users can have instant feedback on errors or success 
---
---
- https://trello.com/c/9sHFYQxH/108-inputs-fix-inputs-with-toast
---
=> [Chore] Added toast notifications for e mail subscriptions 

app/supplements/page.tsx
- added link for supps and changed description
- 
- 
---
to make it more appeadling to the user 
---
---
=> [Chore] Add link for supps and change description

components/ui/contact-form.tsx, package-lock.json, package.json
- added email functionality to the contact us forms 
- 
- 
---
in order to recieve emails 
---
---
---
https://trello.com/c/usPz9OJM/119-email-smtp-for-rise
---
=> [Feature] Added email functionality to the contact us forms

app/games/page.tsx
- 
- styled games card 
- 
---
made it look a bit better 
---
---
---
=> [Refactor] Styled game card on games page

app/barber/page.tsx, components/haircutGallerySection.tsx, services/haircuts.ts
- Changed header
- Fixed extra image bug
- Changed styling
---
- Changed header so it doesn't say haircuts, so it is a gallery for haircuts and the area 
- Added code so the extra image gets filtered out
- Changed styling, took out the description that says what haircut style it is 
---
---
=> [Chore] Fixed Gallery Section

components/contactForm.tsx
-  Fixed the captcha not loading 
- 
- 
---
user would have to refresh the page to see the recaptcha
---
---
---
---
=> [Bugfix]Fixed recaptcha not loading

app/contact/page.tsx, app/supplements/page.tsx, components/ui/plan-comparison-table.tsx, lib/constants.ts
- 
- updated the memberships comparsion table to reflect the correct information 
- 
---
information was previously incorrect 
---
---
---
---
=> [Chore]Updated memeberships comparison table

app/reviews/page.tsx, components/ui/review-card.tsx, components/ui/review-grid.tsx, lib/constants.ts
- Hard coded reviews
- Added view more / write review button
---
- Added reviews so users can read what others are saying 
- Added button so users can go to the google reviews link 
---
---
- https://trello.com/c/HB6sIJ4N/166-hard-code-reviews
---
=> [Chore] Adjusted reviews 

lib/constants.ts
- Changed Jr.Rise full year
- Deleted text from gear package list 
---
- Changed game day jersey to false and deleted text say it is included so Users can have an accurate compare plans table 
---
---
=> [Chore] Fixed Compare plans section

components/newsletter-form.tsx
-  Changed the newsletter api to request the api from the backend
- 
- 
---
Hubspot has to be in the backend not the frontend
---
---
---
https://trello.com/c/JawtWbJa/169-hubspot
---
=> [feature] newsletter integrate with our backend

lib/constants.ts
- Changed link in footer
---
- Changed the link so users will go to the basketball page, if they are on the basketball page it will scroll them to the schedule 
---
---
=> [Chore] Changed schedule link in footer

app/cookies/page.tsx, app/privacy/page.tsx, app/terms/page.tsx
- Restyles Terms, Privacy and cookies 
---
- Restyled them so they look a little cleaner 
---
---
=> [Chore] Restyled our policies

components/event-modal.tsx, components/ui/calendar.tsx, package-lock.json, package.json
- 
- added modal on calendar for users to click 
- 
---
to improve the ux 
---
---
=> [Feature] Added Modal for events to click

components/event-modal.tsx, services/eventsCalendar.ts, types/event.ts
-  Added description to modal 
- 
- 
---
to show information 
---
---
---
=> [Feature] Added description in modal to display information

services/topPlayers.ts
- Added Rise logo on players as default image
---
- Added image so players have a image in case theres no url
---
---
=> [Chore] Added default image for players

app/coffee/page.tsx
- 
- added seo for coffee shop 
- 
---
---
---
---
---
=> [Chore] Added SEO for coffee shop

app/performance/page.tsx
- 
- added seo for performance page 
- 
---
---
---
---
---
=> [Chore] Added Seo for performance page

app/contact/page.tsx, app/supplements/page.tsx
- 
- seo additions 
- 
---
to display better on google 
---
---
---
---
=> [Chore] Added seo to needed pages

next-sitemap.config.js, package-lock.json, package.json, public/robots.txt, public/sitemap.xml
- 
- added seo sitemap for the website 
- 
---
to display on search console 
---
---
---
---
=> [Chore] Configured and added sitemap for seo

components/ui/membership-card.tsx, hooks/useMembershipPlans.ts, services/membership.ts
- 
- changed it to bi weekly
- 
---
because theres no monmthly
---
---
---
---
=> [Refactor] Changed monthly to bi weekly

app/basketball/page.tsx, app/coffee/page.tsx, app/performance/page.tsx
- 
- 
- fix image tags 
---
---
---
---
---
=> [Refactor] Added image tags

components/membershipsSection.tsx, components/performanceMembershipSection.tsx
- 
-  in order to display memberships correctly
- 
---
---
---
---
---
=> [Refactor] Hardcoded ids to display now instead

components/basketballMembershipSection.tsx, components/membershipsSection.tsx
✅ Please prefix your PR title with one of the following:
- [Feature]
- [Bugfix]
- [Refactor]
- [Chore]
- [Docs]
Example:  
`[Feature] Add login screen for mobile app`
---
---
- 
- 
- 
---
---
---
---
---
=> fixed ids issue

components/player-stats.tsx, components/ui/player-stats-card.tsx
---
- 
- 
- removed view stats 
---
---
---
---
---
=> [Refactor] Removed stats card

app/contact/page.tsx, app/page.tsx, app/supplements/page.tsx, components/basketballMembershipSection.tsx, components/partner-logos.tsx, components/ui/membership-card.tsx, lib/constants.ts
- Changed contact information to RISE HQ
- Changed prices for memberships to reflect correct information 
- Added Adult basketball membership 
- Changed Havenz Smart Communities Size 
- Updated stats section on homepage 
---
Requested changes from client
---
---
=> [Chore] Added requested changes for website

components/ui/membership-card.tsx, lib/constants.ts
✅ Please prefix your PR title with one of the following:
- [Feature]
- [Bugfix]
- [Refactor]
- [Chore]
- [Docs]
Example:  
`[Feature] Add login screen for mobile app`
---
---
- 
- 
- 
---
---
---
---
---
=> [Chore] Changed prices to bi-weekly

app/basketball/page.tsx, app/schedule/page.tsx, components/header.tsx, components/schedule/upcoming-highlights.tsx, components/scheduleCalendar.tsx, components/ui/calendar.tsx, lib/constants.ts, package-lock.json, package.json
-  added new schedule page, changed coffee, supplements and barber to ammenties drop down.
-  added upcoming highlights to display events better for users 
-  added filters for different events 
---
stake holder request 
---
- [x ] No server errors (Backend)
---
---
---
=> [Feature] Added schedule page to display better ux for users

components/header.tsx
- Routed Amenities link to the barber page
---
- Made this so when a User clicks on amenities they go to the barber page instead of receiving a page that says 404 not found 
---
---
- https://trello.com/c/Vu9koxhA/224-route-amenities-to-the-barber-page
---
- Some formatting changes
=> [Chore] Routed amenities to the barber page

app/faq/page.tsx, app/layout.tsx, app/page.tsx, components/FAQAccordion.tsx, components/JumpstartModal.tsx, components/ui/feature-card.tsx, components/ui/feature-grid.tsx, components/ui/video-hero.tsx, lib/constants.ts, lib/faqData.ts, lib/gtag.ts
- 
- added google analytics testing, and tags, updated faq page to display more questions for users 
- 
---
stakeholder request 
---
---
---
---
=> [Feature]Added google analytics and updated faq

app/basketball/page.tsx, components/JumpstartModal.tsx
- 
-  fixed the issue where coaches dont display unless refreshed 
- 
---
user experiencec
---
---
---
---
=> [Refactor] Fixed issues with coaches

app/page.tsx, app/schedule/page.tsx, components/ui/membership-card.tsx
✅ Please prefix your PR title with one of the following:
- [Feature]
- [Bugfix]
- [Refactor]
- [Chore]
- [Docs]
Example:  
`[Feature] Add login screen for mobile app`
---
---
- 
- 
- 
---
---
---
---
---
=> [Chore] Added Gtags

app/schedule/page.tsx, services/eventsCalendar.ts
- 
-  changed time zone in order to render events properly 
- 
---
events were not displaying on the front end pane;l 
---
- [ x] Backend APIs tested via Postman
---
---
---
=> [fix] fixed timezone error on public website
